"""DAQ instrument contract (CORE.md §2).

Streaming + reads for analog-in (ai) and digital-in (di). Variables
(read/write) are added in P1.3.
"""

from __future__ import annotations

from typing import Protocol


class DaqContract(Protocol):
    async def ai_stream_start(self, args: dict | None = None) -> dict: ...
    async def ai_stream_stop(self) -> dict: ...
    async def di_stream_start(self, args: dict | None = None) -> dict: ...
    async def di_stream_stop(self) -> dict: ...
    def latest(self, signal: str) -> dict | None: ...
    def is_running(self, signal: str) -> bool: ...

    async def variable_read(self, name: str) -> dict: ...      # -> {value, ts}
    async def variable_write(self, name: str, value: object) -> dict: ...
