"""Health Check contract (CORE.md §2, HEALTH_CHECK.md §11)."""

from __future__ import annotations

from typing import Protocol


class HealthContract(Protocol):
    def list_checks(self) -> list[dict]: ...
    def list_suites(self) -> list[dict]: ...
    async def run(self, *, suite=None, check_ids=None, mode="serial",
                  trigger="manual", operator=None) -> str: ...
    def abort(self, hid: str) -> None: ...
    async def list_runs(self, since=None, limit=None, trigger=None) -> list[dict]: ...
    async def get_run(self, hid: str) -> dict | None: ...
    async def current(self, trigger=None) -> dict | None: ...
