"""Help module contract (CORE.md §2). Read-only doc surface."""

from __future__ import annotations

from typing import Protocol


class HelpContract(Protocol):
    def index(self, *, include_dev: bool) -> list[dict]: ...
    def page(self, page_id: str, *, include_dev: bool) -> dict | None: ...
    def search(self, query: str, *, include_dev: bool) -> list[dict]: ...
    def for_route(self, route: str, *, include_dev: bool) -> dict | None: ...
    def assets(self, *, include_dev: bool) -> list[dict]: ...
    def asset(self, asset_id: str, *, include_dev: bool) -> tuple[bytes, str] | None: ...
    def facts(self, *, include_dev: bool) -> dict | None: ...
